### ISSUE TITLE
Roadmap - things to work on

### ISSUE THREAD

**Issue by timeyyy** [cloudmatrix/esky#90]
This is a road map for anyone who wants to help out
## Issues
- [x] lack of documentation on known issues
- [x] esky fails with py2exe
- [x] getting root on windows 
- [ ] everything in issues/pull requests
- [x] pypi needs to be updated
- [x] pep8 codebase
- [ ] [update registry](https://msdn.microsoft.com/en-us/library/windows/desktop/ee872121%28v=vs.85%29.aspx) or other system meta data after a successful update
## New Features
- [x] travis-ci on linux
- [x] ci on windows
- [ ] ci on mac
- [ ] get python 3.5 tests passing
- [ ] python3 compatible code
- [ ] support pyinstaller
- [ ] use tuf library under the hood for a nice boost in security
- [ ] support code signing
## Refactors
- [ ] Use requests instead of urllib

**Comment by rfk** [comment]
@timeyyy I added you as a collaborator on this project, you should have the ability to push to the repo.  Please continue to PR me for any substantial changes, but if you've got smaller cleanups feel free to make a PR and then merge for yourself without blocking on my feedback.  (Making a PR anyway just helps to increase visibility of what's changing).

Thanks for your work on pushing this project forward after a long period of inactivity!

**Comment by timeyyy** [comment]
@rfk It's a pleasure, great little project you put together here ^^, i will definitely be using the PR system, I'm fairly green so it's better if people are able to look over what i do. I just had a look at travis-ci and i am unable to turn it on for the repo, If you could do that it that would be great. https://travis-ci.org/profile/cloudmatrix

**Comment by rfk** [comment]
Travis should be enabled now.

> are you okay with me dropping support for 2.6 and lower?

I usually *try* to keep 2.6 support if possible, but realize that's getting harder and harder these days.  I'm OK to drop it if it's too much of a maintenance burden.

**Comment by timeyyy** [comment]
@rfk , pre nasty problem atm, a library i am using to write 2/3 compatible code tries to open a data file from the library.zip which fails miserably. There have been a few other problems with the freezers in using the future module. I'm thinking to make a small library that fixes the problems so people can freeze (not just with esky but cxfreeze etc) modules and libraries that use future . At the moment the most unobtrusive solution i can think of is editing the file before we pull it into the library.zip to use pkgutil.find_data to open the files. I can't imagine the change will stop anyone's code from running. Are you ok with this approach?

Another idea which i like less might be to remove the dependency on the part of the code that is causing the errors, which means i would need to manually refactor all the unicode/string/basestring stuff, the downside is that there will be no support for using the future module. (not just with esky but in general)

**Comment by timeyyy** [comment]
@rfk can we get an update on pypi? The current version has known issues. If you need a refresher here is a nice link:
https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

also i am 99% ready to push a version of esky which is python 2/3 compatible, a hold up is that i do not own a mac...

**Comment by rfk** [comment]
@timeyyy thanks for the prompt; v0.9.9 pushed, let me know if you spot any problems with it.

> a hold up is that i do not own a mac

I have a couple of macs at home, I can test something out next week if you like, just leave some instructions here

**Comment by timeyyy** [comment]
@rfk ran into a few more hiccups with the whole 2 to 3 thing.
to overcome a cxfreeze limitation i am extracting a certain python library to sit next to library.zip.

I have ver 1 and ver 2 of an esky with this structure. I want to update ver 1 to version 2 via patching. Unfortunately the applied patch drops the library that i extrcted to sit next to library.zip,

i can easily fudge the solution but just curious if you might know why it's not picking up the changes

**Comment by rfk** [comment]
A couple of random thoughts:

* you may need to include the file in bootstrap-manifest.txt if it's intended to live in the bootstrap env
* if the patcher is deliberately removing it, you may need to tweak to process of how you're generating the patch to ensure it gets preserved, LMK the steps you're using and I may be able to suggest something

**Comment by timeyyy** [comment]
Folder/files are just sitting next to the library.zip not in the bootsrap env.

I am essentially running the tests,

```python
dist_setup(version="0.3",scripts=[script2,script3],options=options,script_args=["bdist_esky_patch"],**metadata)
```
dist_setup is a patched version here that has made the necessary changes, the esky is zipped up
and all is looking swell

```python
        os.unlink(os.path.join(tdir,"dist","eskytester-0.3.%s.zip"%(platform,)))
        #  Check that the patches apply cleanly
        uzdir = os.path.join(tdir,"unzip")
        deep_extract_zipfile(os.path.join(tdir,"dist","eskytester-0.1.%s.zip"%(platform,)),uzdir)
        with open(os.path.join(tdir,"dist","eskytester-0.3.%s.from-0.1.patch"%(platform,)),"rb") as f:
            esky.patch.apply_patch(uzdir,f)
```
however after applying the patch here, the folders that i pulled out of library.zip are being removed

**Comment by timeyyy** [comment]
@rfk ok so i would change that 99% to like 80% ^^, 
python3 will not suck in the MSVCRT,
this line is returning [] on Python3,
https://github.com/cloudmatrix/esky/blob/master/esky/bdist_esky/__init__.py#L590

Note: the old test suite doesn't run on py3 so is it possible it never worked? or has something i done made it go wonky?

**Comment by rfk** [comment]
> this line is returning an empty list on Python3

Doesn't ting a bell unfortunately.  It's entirely possible that the manifest format has changed in newer releases.  You could try just printing out the whole `manifest_str` and grepping for references to "CRT", might give some clues as to what's changed.

**Comment by timeyyy** [comment]
@rfk thanks for the tips always appreciated. I've come across the tuf project recently, http://theupdateframework.com/, its a framework for developing secure update systems, i think pypi and some other people are using it. Would you be able to take a butchers at it and estimate how long it might take (if at all possible) to integrate into esky? I'm a fairly new programmer and would appreciate your input.

**Comment by rfk** [comment]
It looks like it could be a good fit, at first glance the level of abstraction seems to match what we do in esky.  It seems the integration would look something like a `TUFVersionFinder` class, implementing the interface defined by `esky.finder.VersionFiner`, and using the functions exported by the `tuf` module in [1].  Prototyping this seems like a relatively small undertaking - if we're lucky, the two could fit together quite nicely.

If you're keen to dive in and have a go at this, I suggest spinning it off into a separate issue and we can chat more about the details.

[1] https://github.com/theupdateframework/tuf/blob/develop/tuf/client/README.md

**Comment by timeyyy** [comment]
i'll throw this on the todo list for now, i want to get the code base moved over to python3 first.

**Comment by timeyyy** [comment]
@rfk would you want to use waffle for this repo? https://waffle.io/timeyyy/esky

**Comment by rfk** [comment]
I :heart: waffle, sounds good.  I wonder if we should also create a dedicated github org for this project, so that that the canonical repo would be at https://github.com/esky/esky rather than under cloudmatrix (which is from an older commercial venture I was involved with)

**Comment by rfk** [comment]
(btw I'm going to be travelling for work for the next week so I might be even slower to respond than usual...)

**Comment by timeyyy** [comment]
You could even just move the repo under your personal account, cloudmatrix is a cool name but as you will :-)

**Comment by cbenhagen** [comment]
Hi there,

i would recommend to do the pep8 part as fast as possible as this is going to completely mess up the history. As in blame will show almost every line changed by that commit. The faster it is done the faster blame will be useful again.

You might consider using [yapf](https://github.com/google/yapf) to do most of the hard work. Some manual work will still be needed but in most cases it will do a good job.

**Comment by rfk** [comment]
Thanks for reaching out.  Unfortunately this project is no longer actively maintained, so I'm going to move it into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
